### ISSUE TITLE
自动测试问题

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/data-analysis-in-action#17]
仓库的书稿和代码是用 Github Action 提供的测试环境来测试的

#### cmdstanr

- [x]  **cmdstanr** 包目前还未发布在 CRAN 上，只能从 Github 仓库安装开发版或者从指定的开发仓安装。在描述文件中指定额外的仓库地址， r-lib/actions/setup-r-dependencies@v2 并不能识别和使用，显示无法检索到 **cmdtanr** 包，而报错，详见 https://github.com/r-lib/actions/issues/534 。目前是手动添加一段从指定仓库安装 **cmdstanr** 包的代码。

#### r-lib/action

- [x] https://github.com/r-lib/actions 等待上游发布 v3，然后升级

```
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.2.1'

      - uses: r-lib/actions/setup-r-dependencies@v2
```

> 上游已经更新，继续使用 v2

修复 Node 12 警告信息，防止发布失败

#### Quarto

- [x] 等待发布版本 1.2.xxx 

```
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          version: 1.1.251
      - run: |
          quarto --version
          quarto pandoc --version
```

使用最新的稳定版  Quarto 

#### R 包环境管理

- [x] 可能需要引入软件/R包版本管理。先控制住软件环境，完成书籍的编写，然后再考虑环境升级，特别是 tidyverse 相关的 R. 包，比如 ggplot2 和 vctrs 包，写书过程又很漫长，它们相对来说就不那么稳定了，它们对书籍的影响太大了。

#### Dockerfile

- [x] 等 ggplot2 / dplyr 包发布最新稳定版后，初稿完成后（影响书稿的主要因素确定后），制作虚拟环境，让 Github / Binder 都从自定义虚拟环境中启动，固化下来运行环境，以便后续维护。
目前使用的 Dockerfile 环境 binder 来自 https://github.com/rocker-org/binder
